"""
Django settings for ttsx project.
Generated by 'django-admin startproject' using Django 4.2.4.
"""
import os
from pathlib import Path

# 路径配置优化：使用 Path 对象更简洁
BASE_DIR = Path(__file__).resolve().parent.parent

# 安全配置（建议生产环境通过环境变量注入）
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-3c8yk($ypnum5y*u2rs*od_h5f7@^j3h8pfnx^&a6!td$*64vc")
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# 应用定义
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "goods",   # 商品应用
    "cart",    # 购物车/订单应用
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ttsx.urls"

# 模板配置优化：使用 Path 拼接
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # 更简洁的路径写法
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ttsx.wsgi.application"

# 数据库配置（生产环境建议用环境变量）
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "USER": os.environ.get("MYSQL_USER", "root"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", "03260326@"),
        "HOST": os.environ.get("MYSQL_HOST", "localhost"),
        "NAME": os.environ.get("MYSQL_DB", "ttsx"),
        "PORT": int(os.environ.get("MYSQL_PORT", 3306)),
        "OPTIONS": {  # 新增：优化 MySQL 连接
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# 密码验证
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# 国际化
LANGUAGE_CODE = "zh-hans"  # 这个可以不改，不影响运行
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = False  # 关闭时区转换（匹配业务场景）

# 静态文件配置
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# 媒体文件配置（用户上传的图片）
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 默认主键类型
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"