# Generated by Django 4.2.4 on 2026-03-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_sn", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=11)),
                ("freight", models.IntegerField(default=1000)),
                ("remark", models.CharField(blank=True, max_length=200)),
                ("status", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "cart_orderinfo",
            },
        ),
        migrations.CreateModel(
            name="OrderGoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodsinfo",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.orderinfo"
                    ),
                ),
            ],
            options={
                "db_table": "cart_ordergoods",
            },
        ),
    ]
